name = "wcastats-prefetch"
main = "src/index.js"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[triggers]
crons = ["0 8 20 7 *"]

[vars]
POCKETBASE_URL = "https://gp1.pecet.it"
WCA_API_URL = "https://www.worldcubeassociation.org/api/v0"
COUNTRY = "PL"
NOTIFY_EMAIL = "g.pacewicz@gmail.com"
FROM_DOMAIN = "grzegorzpacewicz.pl"
